package sec03_throwsexception.EX03_ThrowsException_3;

//1. 하위 메서드에 직접 예외를 처리할때
class A{
	void abc() {
		bcd();
	}
	void bcd() {
		try {
			Class cls = Class.forName("java.lang.Object");
			Thread.sleep(1000);
		}catch(InterruptedException | ClassNotFoundException e) {
			// 예외 처리 구문
		}
	}
}

class B {
	void abc() {
		try {
			bcd();
		}catch(InterruptedException | ClassNotFoundException e) {
			// 예외 처리 구문
		}
	}
	void bcd() throws InterruptedException, ClassNotFoundException {
		Class cls = Class.forName("java.lang.Object");
		Thread.sleep(1000);
	}
}
public class ThrowsException_3 {
	public static void main(String[] args) {

	}
}
